# This is a basic workflow to help you get started with Actions

name: create document

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  convert_via_pandoc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir
          echo "::set-output name=files::$(printf '"%s" ' manuscript/*.md)"
      - uses: docker://frozenbonito/pandoc-eisvogel-ja:2.10
        with:
          entrypoint: /usr/local/bin/pandoc
          args: --output=output/result.pdf ${{ steps.files_list.outputs.files }}
            --pdf-engine=lualatex
            --listings
            --toc
            -N
            -V documentclass=ltjsarticle
            -V luatexjapresetoptions=ipaex
            -V toc-title="目次"
            -V linkcolor=blue
            -V toc-own-page=true
            -V table-use-row-colors=true
            -V titlepage=true
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
